apiVersion: v1
kind: ConfigMap
metadata:
  name: example-redis-config2
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: test/data/first/argocd/test
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
    db_pass <db_password>
