apiVersion: v1
kind: Secret
metadata:
  name: examplesecret
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: test/data/first/argocd/test
type: Opaque
stringData:
  db_pass: <db_password>
